### ISSUE TITLE
conflict: `ataraxis-lua`

### ISSUE THREAD

**Issue by examosa** [jooooscha/nixpkgs-vim-extra-plugins#4]
There is a duplicate entry for `ataraxis-lua` in [`vim-plugins.nix`](https://github.com/jooooscha/nixpkgs-vim-extra-plugins/blob/main/pkgs/vim-plugins.nix#L2900-L2925) causing errors.

**Comment by jooooscha** [comment]
Thanks for reporting. Should be fixed now.
Unfortunately, the original script that generates the pkgs is not that good. As soon as I have time I will rewrite that script.
